### ISSUE TITLE
Submenu positioning missing in 6.0.0

### ISSUE THREAD

**Issue by nodwyer4** [fkhadra/react-contexify#229]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unstyled submenu no longer has left/right positioning and appears over the top of the current context menu

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
Tried this but ran into X is not a function using the example on react-contextify's website 
https://codesandbox.io/s/upbeat-hamilton-sn3g71

**What is the expected behavior?**
Unstyled submenu appears to the right when there is room for it to display, or on the left if there is no screen space on the right. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.14.0, Chrome, working in version 5.0.0 of react-contextify, broken in 6.0.0
